### ISSUE TITLE
After restart integration requires reconfiguration... sometimes

### ISSUE THREAD

**Issue by dogmatic69** [gjohansson-ST/sector#100]
**Describe the bug**
Seems to have started recently, perhaps the last update. Happens quite often but not always.  

After restarting sometimes the integration is in a broken state saying that it needs to be reconfigured which requires reentering the email/password. Restarting again results in it working (assume flakey network to sector or something like that)

**Version**
Latest everything

**Expected behavior**
After a restart a working integration should still work. If there is a network error in the startup it should retry rather than assume the password is wrong

**Comment by Olen** [comment]
There is a TIMEOUT set to 8 seconds(!) in coordinator.py

https://github.com/gjohansson-ST/sector/blob/5f5f34cd96128b0755c4a585ac21248dc2078970/custom_components/sector/coordinator.py#L16

If login after restart takes more than 8 seconds, it will fail, and the token will not be set.
There is no "retry" if this fails.

Now, I don't know why it is set to 8 seconds, but at least here, it seems like the first request during startup of HA might tak up to 15-20 seconds, probably because they are queued and my HA does a lot of connects on restart.

I changed this to 30, and the problem did not happen again on the next restarts.

The BEST fix is probably to implement some kind of retry.
I made a very naïve attempt by just cloning lines 232 to 236 to do another attempt if the first one fails:
https://github.com/gjohansson-ST/sector/blob/5f5f34cd96128b0755c4a585ac21248dc2078970/custom_components/sector/coordinator.py#L232-L238

```
        if self._access_token is None:
            try:
                await self._login()
            except Exception as error:  # pylint: disable=broad-except
                if "unauthorized" in str(error).lower():
                    raise ConfigEntryAuthFailed from error
                if self._access_token is None:
                    LOGGER.debug("Probably timeout while logging in. Trying again...")
                    try:
                        await self._login()
                    except Exception as error:  # pylint: disable=broad-except
                        if "unauthorized" in str(error).lower():
                            raise ConfigEntryAuthFailed from error
            if self._access_token is None:
                LOGGER.debug("Still no Token. Giving up!")
                raise ConfigEntryAuthFailed
```
But that still caused connection issues on regular basis.

So here, I just changed the TIMEOUT with 30 seconds, and it seems to work ok.  I don't know if it has any side effects though.

**Comment by jlatvala** [comment]
Same problem here also. Does someone have plans to implement better retry functionality?

**Comment by gjohansson-ST** [comment]
There is a retry now in https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta11

**Comment by dogmatic69** [comment]
After installing latest version and restarting I get this error constantly:

```
2022-09-25 10:39:56.263 DEBUG (MainThread) [custom_components.sector] Info retrieved successfully URL: https://mypagesapi.sectoralarm.net/api/account/GetPanelList
2022-09-25 10:39:56.263 DEBUG (MainThread) [custom_components.sector] request status: 200
...
...
...
2022-09-25 10:40:06.114 DEBUG (MainThread) [custom_components.sector] Did not retrieve information properly
2022-09-25 10:40:06.114 DEBUG (MainThread) [custom_components.sector] request status: 401
2022-09-25 10:40:06.114 DEBUG (MainThread) [custom_components.sector] request text: <coroutine object ClientResponse.text at 0xffff6ae7c190>
2022-09-25 10:40:06.114 DEBUG (MainThread) [custom_components.sector] Finished fetching sector data in 10.527 seconds (success: False)
```

After the first time that error showed up there was this error

```
2022-09-25 10:37:43.339 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxx@xxx.com' for sector integration not ready yet: Could not retrieve panel; Retrying in background
```

**Comment by dogmatic69** [comment]
I've since restarted again with no difference. Latest version is completely broken for me

**Comment by jlatvala** [comment]
> After installing latest version and restarting I get this error constantly:

I made a new ticket for this:
https://github.com/gjohansson-ST/sector/issues/111

**Comment by gjohansson-ST** [comment]
Thanks guys. I'll look at this today and try to locate the problem.
Probably need to put in more debugging to get more feedback on what's going on.

**Comment by gjohansson-ST** [comment]
I added a lot of debugging in the coordinator to be able to see what's going on. Could you replace this file only and give it a try [coordinator](https://github.com/gjohansson-ST/sector/blob/master/custom_components/sector/coordinator.py)

Please attach the log-file after to this thread (don't paste the log, attach it).
**Note:** The log does not mask anything. Ensure you scan it and mask what is needed beforehand
**Thanks for your support**

**Comment by gjohansson-ST** [comment]
Thanks. I think I found the problem so I have updated the coordinator again.
Please download (just that file) and replace locally to test it.

Again, thanks for helping out!

**Comment by jlatvala** [comment]
New problem arrived, log attached.

[sector.txt](https://github.com/gjohansson-ST/sector/files/9652033/sector.txt)

**Comment by gjohansson-ST** [comment]
Sorry, stupid mistake. `coordinator.py` updated so please test again

**Comment by gjohansson-ST** [comment]
It sucks when I can't test (and did not implement local tests).
I changed it to fix the problem. Please test again (sorry about that).

**Comment by jlatvala** [comment]
Big thanks for helping to get this working again!!!

Now adding integration goes through, no errors in log (before enabling debug log).

But the box in integrations UI shows text: "Retrying setup: Missing panel_id"
and there is no Sector Alarm devices or entities.

Small note: I found text "Temprature" (one e missing) from log files. Not sure if this mistyped string comes from Sector Alarm or from your codes.

debug log attached

[sector2.txt](https://github.com/gjohansson-ST/sector/files/9654264/sector2.txt)

**Comment by gjohansson-ST** [comment]
Here we go again. I believe it should be fixed now. Again a problem with the panel_id.

> Small note: I found text "Temprature" (one e missing) from log files. Not sure if this mistyped string comes from Sector Alarm or from your codes.

It's from the api. Someone probably misspelled something at development and then it was to late to fix 😄

**Comment by jlatvala** [comment]
Unexpected error fetching sector data: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/sector/coordinator.py", line 227, in _async_update_data
    data[panel]["alarmstatus"] = response_get_status.get("Status")
TypeError: unhashable type: 'dict'

**Comment by gjohansson-ST** [comment]
Try again

**Comment by jlatvala** [comment]
Unexpected error fetching sector data: 'lock'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/sector/coordinator.py", line 246, in _async_update_data
    if data[key]["lock"]:
KeyError: 'lock'

**Comment by gjohansson-ST** [comment]
Try again

**Comment by jlatvala** [comment]
Unexpected error fetching sector data: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/sector/coordinator.py", line 293, in _async_update_data
    data[panel]["changed_by"] = user_to_set if user_to_set else self.logname
TypeError: unhashable type: 'dict'

THANKS for having patience :)

**Comment by gjohansson-ST** [comment]
Thanks. Try again

**Comment by jlatvala** [comment]
🥳🎉

Taking integration into use worked. I got the devices and entities into HA.

I didn't yet have much time
However, when using alarm panel (in HA) to arm the system, this is written into log:
(the system is armed even the error is logged into HA)
(same/similar as https://github.com/gjohansson-ST/sector/issues/101 )

---

Traceback (most recent call last):
  File "/config/custom_components/sector/coordinator.py", line 366, in _request
    output: dict | list = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/Arm')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sector/coordinator.py", line 106, in triggeralarm
    await self._request(API_URL + "/Panel/Arm", json_data=message_json)
  File "/config/custom_components/sector/coordinator.py", line 369, in _request
    raise UpdateFailed from error
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/sector/alarm_control_panel.py", line 129, in async_alarm_arm_away
    await self.coordinator.triggeralarm(
  File "/config/custom_components/sector/coordinator.py", line 114, in triggeralarm
    raise HomeAssistantError from error
homeassistant.exceptions.HomeAssistantError
```

**Comment by gjohansson-ST** [comment]
I modified the code slightly to get some debugging.
Can you download the `coordinator.py` file and replace the one you have.
Turn on debugging and then execute the command again and supply the output from the logs.
There should be two debug lines just above the errors in the log.

**Comment by jlatvala** [comment]
Logs after arming the alarm (using HA UI, alarm panel).
[sector_arm_log.txt](https://github.com/gjohansson-ST/sector/files/9690431/sector_arm_log.txt)

**Comment by gjohansson-ST** [comment]
Thanks. So actually the api doesn't anymore give a response on executing commands. I will do the last changes and release a new version.

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
