### ISSUE TITLE
ContentTypeError / JSON errors while arming/disarming

### ISSUE THREAD

**Issue by jlatvala** [gjohansson-ST/sector#101]
Using v0.3.5-beta10
And logged in correctly in Sector Alarm (because functionality works (but showing errors)).

Calling this service
```
service: alarm_control_panel.alarm_disarm
data:
  code: >-
    {{something_here}}
target:
  entity_id: alarm_control_panel.sector_alarm_keyboard
```

disarms the system but also shows this in the log:
```
ContentTypeError connecting to Sector: , 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/Disarm')
Traceback (most recent call last):
  File "/config/custom_components/sector/coordinator.py", line 269, in _request
    output: dict | list = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/Disarm')

```

And also this kind of another log entry is always written:
```
While executing automation automation.tag_scanned
Traceback (most recent call last):
  File "/config/custom_components/sector/coordinator.py", line 269, in _request
    output: dict | list = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/Disarm')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/sector/alarm_control_panel.py", line 127, in async_alarm_disarm
    await self._hub.triggeralarm(command, code=code, panel_id=self._panel_id)
  File "/config/custom_components/sector/coordinator.py", line 99, in triggeralarm
    await self._request(API_URL + "/Panel/Disarm", json_data=message_json)
  File "/config/custom_components/sector/coordinator.py", line 282, in _request
    raise UpdateFailed from error
homeassistant.helpers.update_coordinator.UpdateFailed
```

Similar errors appear if using sector alarm keyboard from HA UI (to arm or disarm), but still the system arms or disarms correctly.

Note: I have not given the code in the Sector Alarm configuration (so I need to give it every time in service call or HA UI)

**Comment by gjohansson-ST** [comment]
Should be resolved in https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta11

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
