### ISSUE TITLE
Small bug when removing integration; Tries to unload locks even if you don't have any locks

### ISSUE THREAD

**Issue by TheAzzi** [gjohansson-ST/sector#13]
Hi

I'm testing v0.2.0-beta3 and noticed this small bug / unnecessary error when removing the integration.
The integration tries to unload locks even if you didn't have any locks configured, so it generates some unnecessary error messages in the core log:

```
2020-11-05 10:26:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry sa_XXXXXXXX for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 319, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 75, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by gjohansson-ST** [comment]
Resolved in v0.2.0
