### ISSUE TITLE
Sector Yale: Failed to call lock/unlock

### ISSUE THREAD

**Issue by KimNewgarden** [gjohansson-ST/sector#150]
**Describe the bug**
Lock/Unlock function is broken after updating to HA 2023.2.1, 

**Version**
Latest(?)

**Expected behavior**
Lock/unlock Yale according to schedual or manual change

**Additional context**
[140203855223184] Code '*XXXXXX*' for unlocking Sector Yale «ID» doesn't match pattern ^\d6$
140203855223184] Code '' for unlocking Sector Yale «ID» doesn't match pattern ^\d6$

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 681, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 721, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 102, in _async_unlock
    raise ValueError(

**Comment by unsmian** [comment]
I am seeing the same issue with not being able to use lock/unlock feature through HA.

**Comment by t112013** [comment]
same here. anyone knows what its going on with the development ? seems that it havnt been updates in a long time.

**Comment by LazyTarget** [comment]
Just got annoyed of this issue myself, and checked if it was happening to someone else.

I am a .NET developer, with some dabbing at Python. I think I know where the issue lies. I could post a pull request on it tomorrow

**Comment by LazyTarget** [comment]
@DuoIInto @unsmian  @t112013 
If you want the fix immediately, you could do the same code change in your local `custom_components` folder

**Comment by t112013** [comment]
Jepp. your fix worked, thanks a lot for your input. :)

**Comment by unsmian** [comment]
@LazyTarget 

Hej Peter. I updated lock.py according to your commit (row 66) but still can’t get it to work? I have restarted HA after making the change.

**Comment by LazyTarget** [comment]
> @LazyTarget 
> 
> Hej Peter. I updated lock.py according to your commit (row 66) but still can’t get it to work? I have restarted HA after making the change.

Do you get another error message now?

**Comment by unsmian** [comment]
@LazyTarget Yes, 6 digits (works fine for arming/disarming the Sector alarm) but no joy with the lock.

**Comment by Borge85** [comment]
Any update on this?

**Comment by Ungjaevel** [comment]
![image](https://github.com/gjohansson-ST/sector/assets/618917/d5765e79-c02f-4538-86fd-f4c436f25496)

+1 any update? Annoying that it just stopped. Have changed line 66 in lock.py as per above. No change.

**Comment by unsmian** [comment]
@gjohansson-ST 

Hej!

Any plans on updating this with the above fix?
