### ISSUE TITLE
"Unknown error occured" during setup

### ISSUE THREAD

**Issue by hnrkgrln** [gjohansson-ST/sector#20]
Hello!

I'm getting an error "Unknown error occured" when press submit in the integrations setup dialog. No matter which fields are fill och ticked.

I'm on the latest HA, HACS and Sector. I have never tried Sector before, so their should not be any old configs lying around.

**Comment by gjohansson-ST** [comment]
Could you submit the relevant section from your log file?
Thanks

**Comment by hnrkgrln** [comment]
`2021-01-02 18:34:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/sector/config_flow.py", line 129, in async_step_user
CONF_CODE_FORMAT: user_input[CONF_CODE_FORMAT].replace(" ", ""),
AttributeError: 'int' object has no attribute 'replace'`

**Comment by gjohansson-ST** [comment]
Fixed in release v0.3.1
You should see it in HACS shortly so you can update before you try to configure the integration again.
