### ISSUE TITLE
Getting stack trace in logs about temperature sensors

### ISSUE THREAD

**Issue by robinsmidsrod** [gjohansson-ST/sector#22]
After upgrading to version 0.3.1 I'm getting these stack traces over and over again in my Home Assistant logs:

```
2021-01-17 21:46:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 245, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/sector/sensor.py", line 91, in state
    self._state = self._hub.temp_state[self._serial]
KeyError: '24XXXXXX7B'
```

I'm getting them for different values in KeyError. They seem to disappear some hours after Home Assistant was restarted. Is it possible to restore state for the temperature sensors if they are unavailable during startup instead of throwing these exceptions in the log? Alternatively, set the state value to "unknown" if the Sector Alarm API can't tell you what it is supposed to be?

**Comment by gjohansson-ST** [comment]
This will be addressed in the next release.
You can help by testing the v0.3.3-beta1 release coming out shortly.
Will leave this case open for a week until the actual release

**Comment by robinsmidsrod** [comment]
@gjohansson-ST I just installed the beta release you mentioned and restarted HA. I'm still getting the stack trace:

```
2021-04-11 10:47:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 130, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 295, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 341, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/sector/sensor.py", line 100, in device_state_attributes
    state = self._hub.temp_state[self._serial]
KeyError: '24XXXXXX77B'
```

**Comment by gjohansson-ST** [comment]
Apparently I had it two places so now also number 2 correct.
Install the latest beta v0.3.3-beta2 released shortly to check.
Appreciate all feedback
