### ISSUE TITLE
Switch beta 0.3.4 beta 3

### ISSUE THREAD

**Issue by MrDuco** [gjohansson-ST/sector#38]
Tested the beta 0.3.4 beta 3
Removed old Sector component and redownloaded the new. In integartion this is shown.
![image](https://user-images.githubusercontent.com/57446374/144717549-6e7577c2-8eea-4245-8eec-8fa820094a69.png)

From CORE Logs

2021-12-04 17:44:52 ERROR (MainThread) [custom_components.sector] Unexpected error fetching sector_api data: 'Serial'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 112, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/__init__.py", line 396, in fetch_info
    self._switchstatus = {
  File "/config/custom_components/sector/__init__.py", line 397, in <dictcomp>
    switch["Serial"]: switch["Status"] for switch in self._switchdata
KeyError: 'Serial'
2021-12-04 17:45:12 ERROR (MainThread) [custom_components.sector] Unexpected error fetching sector_api data: 'Serial'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 112, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/__init__.py", line 396, in fetch_info
    self._switchstatus = {
  File "/config/custom_components/sector/__init__.py", line 397, in <dictcomp>
    switch["Serial"]: switch["Status"] for switch in self._switchdata
KeyError: 'Serial'

**Comment by gjohansson-ST** [comment]
New beta to test (beta4)

**Comment by MrDuco** [comment]
Downloaded and re-installed. This is now seen in log:
2021-12-05 14:19:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry sa_02829975 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 79, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/sector/switch.py", line 51, in <module>
    class SectorAlarmSwitch(CoordinatorEntity, SwitchEntity):
  File "/config/custom_components/sector/switch.py", line 78, in SectorAlarmSwitch
    def extra_state_attributes(self) -> dict(str, str):
TypeError: dict expected at most 1 argument, got 2

**Comment by gjohansson-ST** [comment]
> Downloaded and re-installed. This is now seen in log: 2021-12-05 14:19:29 ERROR (MainThread) 

Not funny as I spotted it already yesterday but apparently forgot to fix it in switch while it's fixed in the other platforms.
Now released beta5 fixing this

**Comment by MrDuco** [comment]
Ok, no errors in log now. but no switches can be found in HA. Tried looking for them in dev. tools and also during installation of Sector they are not shown (may they should not be shown here?)
![image](https://user-images.githubusercontent.com/57446374/144753273-a8b7ef90-7c72-44fa-9742-982822280f28.png)

**Comment by gjohansson-ST** [comment]
Ok, I was resetting my own list so therefore no switches appearing.
New beta released which I really hope should now also show the switches.
Thanks for making an effort testing my stuff!

**Comment by MrDuco** [comment]
No, thank you for making this effort even thou not using sector anymore!
This is now shown in log
2021-12-05 17:32:15 ERROR (MainThread) [homeassistant.components.switch] Error while setting up sector platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/switch.py", line 38, in async_setup_entry
    identification = await sector_hub.get_id(switch)
  File "/config/custom_components/sector/__init__.py", line 241, in get_id
    return switch["id"]
KeyError: 'id'

**Comment by gjohansson-ST** [comment]
Simple *** misspelling...
New beta made

**Comment by MrDuco** [comment]
With beta-7
2021-12-05 22:32:44 ERROR (MainThread) [homeassistant.components.switch] Error while setting up sector platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/switch.py", line 41, in async_setup_entry
    switchlist.append(SectorAlarmSwitch(sector_hub, coordinator, description))
  File "/config/custom_components/sector/switch.py", line 64, in __init__
    self._id: str = self._hub.get_id[self._serial]
TypeError: 'method' object is not subscriptable

**Comment by gjohansson-ST** [comment]
Beta 8 released.
Pretty close now to work... Almost guessing here this will be the last beta 🤞

**Comment by MrDuco** [comment]
Sorry. still some new errors in log:
2021-12-06 19:07:20 ERROR (MainThread) [custom_components.sector] Timed out when connecting to Sector
2021-12-06 19:07:35 ERROR (MainThread) [custom_components.sector] Timed out when connecting to Sector
2021-12-06 19:07:47 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: switch.hallen_nere).attributes.Id=<coroutine object SectorAlarmHub.get_id at 0x7f1f75ac1640>(<class 'coroutine'>
2021-12-06 19:07:47 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: switch.koket).attributes.Id=<coroutine object SectorAlarmHub.get_id at 0x7f1f75ac16c0>(<class 'coroutine'>
2021-12-06 19:07:47 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: switch.vardagsrum).attributes.Id=<coroutine object SectorAlarmHub.get_id at 0x7f1f75ac1740>(<class 'coroutine'>

**And then there is this which I don't know if it needs to be handled because I think it is one of my switches that are inactive state, but it fills the log.**
2021-12-06 19:07:47 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform sector
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/sector/sensor.py", line 90, in state
    return self._hub.temp_state[self._serial]
KeyError: '24901XXXXXX'

And unfortunately all of them are marked as unavailable
![image](https://user-images.githubusercontent.com/57446374/144900015-4829ed5a-9d3d-4a5e-a8bb-3a50803c0af4.png)

**Comment by Ubiquitous-X** [comment]
One thing to watch out for are those infamous soft bans Sector hands out like it was candy. Those first two lines you got there, with the "timed out when connecting to Sector" message, with 15 seconds in between, might be that you got banned. That might be why Home Assistant can't add the entities.
Those soft bans are usually lifted after a few hours. But it is on a per device level, so you are probably still able to connect with your Sector app as usual.

**Comment by MrDuco** [comment]
Tried to do some debugging on my own.
To get rid of the JSON serialze error I changed in switch.py line 64
from:
self._id: str = self._hub.get_id(self._serial)
to:
self._id: str = self._hub._switchid[self._serial]

in _init_.py on line 290 and 295 I think there is a typo
was
f"{API_URL}TurnOffSmartplug?switchId={identity}&panelId={self._panel_id}",
and it think it should be_:
f"{API_URL}/Panel/TurnOffSmartplug?switchId={identity}&panelId={self._panel_id}",


Now I can see that is tries to send to Secotr but status of the Switch does not change and it reverts back in UI to "on" no matter what state switch is in.

**Comment by gjohansson-ST** [comment]
Ok. Did a beta9 release now. I would think it should fix the issue.
Given I have changed a lot of things e.g. cleanup make sure you test state and control on all stuff so not only switch.

**BETA 9 REQUIRES HA 2012.12 so make sure you update to it before running beta9**

**Comment by MrDuco** [comment]
Unfortunatlly this caused the temprature sensors to report "Unknown"
![image](https://user-images.githubusercontent.com/57446374/146070607-00c947dc-b0e9-4af7-9c65-4f57ec1ab4bc.png)

Switch can not be controlled (not turned on or off) and Status is not updated (when turned on from Sector mypages). They just reset to "off" state in UI.
![image](https://user-images.githubusercontent.com/57446374/146070920-f4045237-e594-42ec-99eb-e2fdee1386a6.png)

**Comment by gjohansson-ST** [comment]
Do you have 2012.12 version of HA (given the temp issue above)?

**Comment by MrDuco** [comment]
Do you mean 2021.12 version or Above?
I have two HA servers on for dev
![image](https://user-images.githubusercontent.com/57446374/146193693-cd3ccca6-2bca-4f1e-8d13-772683a5643c.png)

And my prod HA
![image](https://user-images.githubusercontent.com/57446374/146193890-6b9dbac7-d04c-4a06-a7eb-12a555196afb.png)

both have same issue...

**Comment by gjohansson-ST** [comment]
Yeah. I meant 2021.12
I did do beta10 in the meantime just to fix the sensor and the await problem you made a PR for.
Does the plug itself work with pressing the switch in HA e.g. it acutally does turn on or off when you press?
When you say it reverts to previous state if you leave it does it then change again to the correct state?

**Comment by MrDuco** [comment]
Yes the plug works so it does really turn on or off when I click the switch in HA.
Switch in HA UI after reboot (On):
![image](https://user-images.githubusercontent.com/57446374/146201920-9905fd59-7c2e-46ac-b3e1-af38d2aa2e21.png)

The plug (On), correct!
![image](https://user-images.githubusercontent.com/57446374/146202621-b676c370-b3ca-4cd6-8705-009832784e02.png)

Then I turn it "Off" in UI:
![image](https://user-images.githubusercontent.com/57446374/146202698-1dd09744-077c-4fe2-bdcd-501a149c0c6a.png)

And the plug goes to turns "Off", correct
![image](https://user-images.githubusercontent.com/57446374/146202835-46e30f25-9fe9-4baa-b67e-cd9e4449bd0d.png)

So far everything is working as expected!

But then after a few seconds, switch in UI reverts to previous state, in this case "On"
![image](https://user-images.githubusercontent.com/57446374/146203001-a9c4d2bc-11e6-44bd-8a9c-8e95f51a7784.png)

But the plug is still "Off"
![image](https://user-images.githubusercontent.com/57446374/146203300-4beed0c5-d1ee-4d69-9579-62503f9cee81.png)

And waiting, (10 minutes now), refreshing or changing tabs in HA does not update the state either, only way to get switch and plug in sync again is to restart server.

**Comment by gjohansson-ST** [comment]
Very strange.
Can you turn on debug on sector component and check the log (doing same as above). You should see a line starting with "self._switchdata =" where it should say the output from sector api. Especially interesting to see this when it's out of sync.

**Comment by MrDuco** [comment]
Ok, I think I manged to get it. Attached is full log also.

But in short it looks like this

Start up:
2021-12-15 15:10:00 DEBUG (MainThread) [custom_components.sector] self._switchdata = [{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'X', 'Label': 'Hallen nere', 'PanelId': None, 'SerialNo': 'X', 'Scenarios': None, 'Status': 'Off', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}, **{'Consumption': '0', 'DisplayScenarios': False, 'Id': 'Y', 'Label': 'Köket', 'PanelId': None, 'SerialNo': 'Y', 'Scenarios': None, 'Status': 'On', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}**, {'Consumption': '2', 'DisplayScenarios': False, 'Id': 'Z', 'Label': 'Vardagsrum', 'PanelId': None, 'SerialNo': 'Z', 'Scenarios': None, 'Status': 'On', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}]

Then when I click in UI to swtich:
2021-12-15 15:10:35 DEBUG (MainThread) [custom_components.sector] self._switchdata = [{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'X', 'Label': 'Hallen nere', 'PanelId': None, 'SerialNo': 'X', 'Scenarios': None, 'Status': 'Off', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}, **{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'Y', 'Label': 'Köket', 'PanelId': None, 'SerialNo': 'Y', 'Scenarios': None, 'Status': 'Off', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}**, {'Consumption': '2', 'DisplayScenarios': False, 'Id': 'Z', 'Label': 'Vardagsrum', 'PanelId': None, 'SerialNo': 'Z', 'Scenarios': None, 'Status': 'On', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}]

And then after 1 minute:
2021-12-15 15:10:41 DEBUG (MainThread) [custom_components.sector] self._switchdata = [{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'X', 'Label': 'Hallen nere', 'PanelId': None, 'SerialNo': 'X', 'Scenarios': None, 'Status': 'Off', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}, **{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'Y', 'Label': 'Köket', 'PanelId': None, 'SerialNo': 'Y', 'Scenarios': None, 'Status': 'Off', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}**, {'Consumption': '2', 'DisplayScenarios': False, 'Id': 'Z', 'Label': 'Vardagsrum', 'PanelId': None, 'SerialNo': 'Z', 'Scenarios': None, 'Status': 'On', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}]

[debug_log.txt](https://github.com/gjohansson-ST/sector/files/7720603/debug_log.txt)

**Comment by gjohansson-ST** [comment]
Can you confirm id and serialno is different on the three different plugs you have (since you masked it)?

**Comment by MrDuco** [comment]
yes all are different

**Comment by cttime** [comment]
> Yes the plug works so it does really turn on or off when I click the switch in HA. Switch in HA UI after reboot (On): ![image](https://user-images.githubusercontent.com/57446374/146201920-9905fd59-7c2e-46ac-b3e1-af38d2aa2e21.png)
> 
> The plug (On), correct! ![image](https://user-images.githubusercontent.com/57446374/146202621-b676c370-b3ca-4cd6-8705-009832784e02.png)
> 
> Then I turn it "Off" in UI: ![image](https://user-images.githubusercontent.com/57446374/146202698-1dd09744-077c-4fe2-bdcd-501a149c0c6a.png)
> 
> And the plug goes to turns "Off", correct ![image](https://user-images.githubusercontent.com/57446374/146202835-46e30f25-9fe9-4baa-b67e-cd9e4449bd0d.png)
> 
> So far everything is working as expected!
> 
> But then after a few seconds, switch in UI reverts to previous state, in this case "On" ![image](https://user-images.githubusercontent.com/57446374/146203001-a9c4d2bc-11e6-44bd-8a9c-8e95f51a7784.png)
> 
> But the plug is still "Off" ![image](https://user-images.githubusercontent.com/57446374/146203300-4beed0c5-d1ee-4d69-9579-62503f9cee81.png)
> 
> And waiting, (10 minutes now), refreshing or changing tabs in HA does not update the state either, only way to get switch and plug in sync again is to restart server.

If you look at MrDuco'first screenshot you can see the switch is on without any gray highlight (see photo 3 "off"). I see the same issue that the status doesn't change. A button card does not  turn the switch on or off (usually) but if I go into the device page I can select on or off. Before the status will update (and allow a change again) I must click somewhere away from the switch so that the gray around the switch disappears. Once I have done this the status will update and I can change the switch once again.

**Comment by gjohansson-ST** [comment]
Hi guys
Do think it's now sorted in the beta I just made. Give it a try and report back.

**Comment by MrDuco** [comment]
I have done some testing and from what I can see it now seems to work as expected!
@gjohansson-ST - excellent work!  thanks!

**Comment by gjohansson-ST** [comment]
> I have done some testing and from what I can see it now seems to work as expected! @gjohansson-ST - excellent work! thanks!

Let's keep the beta for some days so we see everything works as expected. I can post a new proper release between Christmas and New year if I don't hear anything from you.

**Comment by gjohansson-ST** [comment]
Solved in latest release v0.3.4
