### ISSUE TITLE
Unknown error occurred  on setup

### ISSUE THREAD

**Issue by bmlyng** [gjohansson-ST/sector#56]
I get Unknown error occurred under setup when i press send inn.

From log:
Denne feilen stammer fra en tilpasset integrasjon.

Logger: aiohttp.server
Source: custom_components/sector/config_flow.py:79
Integration: Sector Alarm (documentation, issues)
First occurred: 16:38:59 (2 occurrences)
Last logged: 16:47:32

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/sector/config_flow.py", line 107, in async_step_user
    panel_id = await validate_input(self.hass, userid, password)
  File "/config/custom_components/sector/config_flow.py", line 79, in validate_input
    panel_data = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/getFullSystem')

**Comment by einarsi** [comment]
Getting the same error here.

**Comment by gjohansson-ST** [comment]
Looks like when it's incorrect credentials (username and password) it shows a webpage instead of giving a 404.
Will check how to fix that in the code but check your credentials.

**Comment by einarsi** [comment]
I have just now checked and triple-checked that my credentials are correctly entered. When I click "Submit", I get `Unknown error occurred`and the below is entered in the log.

It may be worth mentioning that I live in Norway. Based on the error message reported by @bmlyng, I guess he does too (?). Please let me know if there is anything I can do to help you bugtest this.

```Log Details (ERROR)
This error originated from a custom integration.
Logger: aiohttp.server
Source: custom_components/sector/config_flow.py:80
Integration: Sector Alarm ([documentation](https://github.com/gjohansson-ST/sector/blob/master/readme.md), [issues](https://github.com/gjohansson-ST/sector/issues))
First occurred: 00:14:41 (3 occurrences)
Last logged: 00:15:36

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/sector/config_flow.py", line 108, in async_step_user
    panel_id = await validate_input(self.hass, userid, password)
  File "/config/custom_components/sector/config_flow.py", line 80, in validate_input
    panel_data = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://mypagesapi.sectoralarm.net/api/Panel/getFullSystem')```

**Comment by gjohansson-ST** [comment]
If you can run [this](https://github.com/gjohansson-ST/sector/blob/master/api-info/api_info.py) and provide the output/errors (remember to mask any sensitive output)

**Comment by einarsi** [comment]
I cloned the repo to a virtual machine with Python 3.10.4, executed "pip install aiohttp", and filled out the UserId and Password in api_info.py. Running the script gives the following:
```➜ develop api-info git:(master) ✗ [.venv] python api_info.py
/home/einar/src/sector/api-info/api_info.py:115: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
2022-06-05 15:30:53.376534
2022-06-05 15:30:54.201556
Funkar inte
Traceback (most recent call last):
  File "/home/einar/src/sector/api-info/api_info.py", line 116, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/einar/src/sector/api-info/api_info.py", line 54, in main
    PANELID = firstrun['Panel']['PanelId']
UnboundLocalError: local variable 'firstrun' referenced before assignment```

Adding a print of response.status before line 50 gives 401 (Unauthorized). I am 100% certain the email/password is correct - I even copy-pasted the email address and password I used in api_info.py to the login prompt at minside.sectoralarm.no and was successfully logged on. I also intentionally entered the wrong password, which caused an earlier error on line 36.

**Comment by gjohansson-ST** [comment]
Do you happen to have any two-factor auth in Norway or something as such?
Maybe just after line 32 do a print of data_out and see if there is something more than just the token itself which can tell us something.

**Comment by einarsi** [comment]
No, there is no 2FA.

There are some items in the output that may be of interest:
`'UserId': 0` <- 0 seems odd, although 'Id' in the same section (User) is a lengthy hash.
`'PanelFeatureAccess': {}` 
`'DefaultPanelId': None`

Other than that, everything seems to have expected or at least reasonable values. 

I then went ahead and commented out lines 54-57 and added "PANELID = " with my system id as a string. Now I get a bunch of information from GetPanelStatus, GetTemperatures, GetLockStatus and GetLogs. So it looks as if it's just /Panel/getFullSystem that fails.

**Comment by gjohansson-ST** [comment]
> Edit: Is it an option to not use getFullSystem and instead let the user input systemid/panelid as an (optional) input when configuring the integration?

That was sort of the plan or at least figure out the different panels and add multiple alarms.
Still I don't necessarily want to have people need to figure out their panel id to use the integration if possible.

Could you test the following?
- Apply your panel id to `getFullSystem` and see if there is provided output then
- Can you run `GetPanel` without the panel id

Great if you could provide the output (masked) to me.
Thanks

**Comment by einarsi** [comment]
Both `API_URL + "/Panel/getFullSystem?panelId={}".format(PANELID)"` and `API_URL + "/Panel/GetPanel"` result in a 401 error.

**Comment by gjohansson-ST** [comment]
Are you using the master account?

**Comment by einarsi** [comment]
Yes

**Comment by gjohansson-ST** [comment]
Super strange I have to say...
Could you perhaps check with developer tools in your browser when you use the website instead and possibly it will tell which endpoints it's using and what it is submitting.

Does `GetPanel` work if you add the panelid to it?

As a last resort I guess we have to drop the full system and use the other endpoints instead but don't understand really why it works for some but for others not. Could have guessed on 2-factor auth, not master account or something as such but apparently not.

**Comment by einarsi** [comment]
Yes, `GetPanel` works when I add my panelid, not without.

I am not familiar with the developer tools, and not sure what to look for or how to interpret it. But I hit F12, clicked around a bit and found stuff such as this under the Network tab. Looks like they all use the same main URL, and all received status code 200. 
`https://mypagesapi.sectoralarm.net/api/Panel/GetPanelStatus?panelId=MASKED`
`https://mypagesapi.sectoralarm.net/api/Panel/GetLogs?panelId=MASKED`

I also noticed `/Login/GetUser` which contains `DefaultPanelId`. Looks like maybe it can be used to fetch PanelId instead of `getFullSystem`?

There were other interesting endpoints there, e.g. `/v2/housecheck/temperatures`, `/housecheck/doorsandwindows`, `/housecheck/smokedetectors`, although I am sure you are already familiar with them. 

If you need anything else from the developer tools, please provide some brief instructions on what I should do to obtain the information.

**Comment by gjohansson-ST** [comment]
You can send any output to me in an e-mail if you prefer, or paste a link to it if you post it on some dump website.

**Comment by robinsmidsrod** [comment]
@gjohansson-ST Just mentioning something I've seen before from the Sector API; when the service is down in some way, they tend to return text/plain responses for payloads which you expect JSON. This could be a way to detect that their API is unavailable and retry later. It could also mean that the API endpoint was removed/no longer supported.

**Comment by gjohansson-ST** [comment]
> @gjohansson-ST Just mentioning something I've seen before from the Sector API; when the service is down in some way, they tend to return text/plain responses for payloads which you expect JSON. This could be a way to detect that their API is unavailable and retry later. It could also mean that the API endpoint was removed/no longer supported.

Yes. I am implementing a way to deal with the and provide the text into the log so it's readable and thereby it can be handled.

**Comment by einarsi** [comment]
> You can send any output to me in an e-mail if you prefer, or paste a link to it if you post it on some dump website. Appreciate the support!

Don't mention it - this is purely out of self interest to get a working Sector integration :) Thank you for all the work you have already put in and for your willingness to update the code to work for me and other people 👍🏻 

I've sent you an email with lots of data - hope it is useful!
