### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by dogmatic69** [gjohansson-ST/sector#73]
Upgraded to latest beta and get this migration error 

```
Error migrating entry sa_02831351 for sector
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_migrate
    result = await component.async_migrate_entry(hass, self)
  File "/config/custom_components/sector/__init__.py", line 42, in async_migrate_entry
    CONF_USERNAME: entry.data[CONF_USERNAME],
KeyError: 'username'
```

**Comment by gjohansson-ST** [comment]
https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta4

**Comment by dogmatic69** [comment]
Still does not work
```
Logger: homeassistant.config_entries
Source: config_entries.py:559
First occurred: 5 June 2022, 23:15:14 (1 occurrences)
Last logged: 5 June 2022, 23:15:14

sector.async_migrate_entry did not return boolean
```

**Comment by dogmatic69** [comment]
After restarting HA there are no errors but the alarm is "unavailable". 

Curiously there are logs indicating that it's getting status...

```
2022-06-06 11:44:30 DEBUG (MainThread) [custom_components.sector] Info retrieved successfully URL: https://mypagesapi.sectoralarm.net/api/Panel/getFullSystem
2022-06-06 11:44:30 DEBUG (MainThread) [custom_components.sector] request status: 200
2022-06-06 11:44:30 DEBUG (MainThread) [custom_components.sector] self._last_updated_temp = 2022-06-06 07:44:23.245396
2022-06-06 11:44:30 DEBUG (MainThread) [custom_components.sector] self._timesync * 5 = 300
2022-06-06 11:44:30 DEBUG (MainThread) [custom_components.sector] Evaluate should temp sensors update 2:00:07.403489
2022-06-06 11:44:33 DEBUG (MainThread) [custom_components.sector] Info retrieved successfully URL: https://mypagesapi.sectoralarm.net/api/Panel/GetPanelStatus?panelId=xxxx
2022-06-06 11:44:33 DEBUG (MainThread) [custom_components.sector] request status: 200
2022-06-06 11:44:33 DEBUG (MainThread) [custom_components.sector] self._alarmstatus = 1
2022-06-06 11:44:33 DEBUG (MainThread) [custom_components.sector] Full output panelstatus: {'IsOnline': True, 'StatusTime': '2022-06-06T08:52:43', 'Status': 1, 'AnnexStatus': 0}
2022-06-06 11:44:34 DEBUG (MainThread) [custom_components.sector] Info retrieved successfully URL: https://mypagesapi.sectoralarm.net/api/Panel/GetLogs?panelId=xxxx
2022-06-06 11:44:34 DEBUG (MainThread) [custom_components.sector] request status: 200
2022-06-06 11:44:34 DEBUG (MainThread) [custom_components.sector] self._changed_by = xxxx
2022-06-06 11:44:36 DEBUG (MainThread) [custom_components.sector] Info retrieved successfully URL: https://mypagesapi.sectoralarm.net/api/Panel/GetSmartplugStatus?panelId=xxxx
2022-06-06 11:44:36 DEBUG (MainThread) [custom_components.sector] request status: 200
2022-06-06 11:44:36 DEBUG (MainThread) [custom_components.sector] self._switchdata = [{'Consumption': '-1', 'DisplayScenarios': False, 'Id': 'xxxx', 'Label': 'Smtplg 1', 'PanelId': None, 'SerialNo': 'xxxx', 'Scenarios': None, 'Status': 'Unreachable', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}]
2022-06-06 11:44:36 DEBUG (MainThread) [custom_components.sector] Finished fetching sector_api data in 13.670 seconds (success: True)
```

**Comment by gjohansson-ST** [comment]
https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta6
