### ISSUE TITLE
Getting closer...

### ISSUE THREAD

**Issue by Olen** [gjohansson-ST/sector#89]
After updating to beta9 I was asked to reauth, and then I got a bit further:

```
2022-06-12 00:00:27 ERROR (MainThread) [custom_components.sector] Unexpected error fetching sector_api data: 'ReadyToArm'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 91, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/coordinator.py", line 137, in fetch_info
    self.api_data[panel]["arm_ready"] = response_get_status["ReadyToArm"]
KeyError: 'ReadyToArm'
```

All of those should probably be wrapped in `dict.get()` with some sane defaults. 

Should have made a PR or two here, but it's getting late, so hopefully you will have this fixed soon.

**Comment by gjohansson-ST** [comment]
Probably you are right. It seems Sector is changing their api information a bit since I was sent info from someone that has this attribute but it seems you don't and I didn't compare new and old good enough.
I will look at this a bit more careful in the morning and post a new beta.

Appreciate your help on testing and reporting back 👍 💯
