### ISSUE TITLE
NoneTypes from API handled as dicts

### ISSUE THREAD

**Issue by einarsi** [gjohansson-ST/sector#95]
Probably related to issue #89 and PR #90, I have seen these errors logged since yesterday, using 0.3.5-beta10:

```Logger: custom_components.sector
Source: custom_components/sector/coordinator.py:135
Integration: Sector Alarm ([documentation](https://github.com/gjohansson-ST/sector/blob/master/readme.md), [issues](https://github.com/gjohansson-ST/sector/issues))
First occurred: 07:25:26 (1 occurrences)
Last logged: 07:25:26

Unexpected error fetching sector_api data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 91, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/coordinator.py", line 135, in fetch_info
    self.api_data[panel]["alarmstatus"] = response_get_status.get("Status")
AttributeError: 'NoneType' object has no attribute 'get'
```

```Logger: custom_components.sector
Source: custom_components/sector/coordinator.py:129
Integration: Sector Alarm ([documentation](https://github.com/gjohansson-ST/sector/blob/master/readme.md), [issues](https://github.com/gjohansson-ST/sector/issues))
First occurred: 13:34:20 (1 occurrences)
Last logged: 13:34:20

Unexpected error fetching sector_api data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 91, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/coordinator.py", line 129, in fetch_info
    self.logname = response_getuser.get("User", {}).get("UserName")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by gjohansson-ST** [comment]
Good catch. Will implement some checks that there is data returned. 
I would have expected it to actually raise some exception but clearly responding but with no data then.

**Comment by Olen** [comment]
Another one to check:

```
2022-06-14 12:35:48 ERROR (MainThread) [custom_components.sector] Error requesting sector_api data: [Errno 104] Connection reset by peer
2022-06-14 12:35:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
    update_callback()
  File "/config/custom_components/sector/alarm_control_panel.py", line 153, in _handle_coordinator_update
    self._attr_state = ALARM_STATE_TO_HA_STATE[
KeyError: None
```

Sorry I don't have time to investigate or create a PR right now, but it seems related to all the other ones.
